version: 0.2
phases:
  install:
    runtime-versions:
      python: 3.7
    commands:
      - echo "Starting install - $(date)"

      - echo "Installing CloudFormation template linting tool cfn-lint"
      - pip install cfn-lint
      - pip install aws-sam-cli
      - pip install pylint
      - pip install iniconfig==1.0.0
      - pip install pytest

      - echo "Completed install - $(date)"
  pre_build:
    commands:
      - echo "Starting pre_build - $(date)"
      - echo "Completed pre_build - $(date)"
  build:
    commands:
      - echo "Starting build - $(date)"

      - echo "Linting CloudFormation template"
      - cd $CODEBUILD_SRC_DIR/function/
      - pwd
      - pip freeze > requirements.txt
      - pip install -r requirements.txt
      - cd $CODEBUILD_SRC_DIR
      - cfn-lint --version
      - sam build --template-file ${TEMPLATE_PATH}
      # https://github.com/aws-cloudformation/cfn-python-lint/issues/1265#issuecomment-568525313
      - cfn-lint --ignore-checks W3011 -t template.yml
      - sam package --template-file .aws-sam/build/template.yaml --kms-key-id alias/aws/s3 --s3-bucket ${S3_DEPLOY_BUCKET} --output-template-file ${TEMPLATE_PATH}
      
      - echo "Completed build - $(date)"
  post_build:
    commands:
      - echo "Starting post_build - $(date)"
      - echo "Completed post_build - $(date)"
artifacts:
  files:
    - ${TEMPLATE_PATH}
    - ${PARAMETER_FILE_NAME}
  discard-paths: no
